defaults:
  # Max. brush size, does not use FAWE's brush size!
  size: 15
  intensity: 4
  imgloresize: 20
  # true = up, false = down
  directionMode: true
  3dmode: false
  flatmode: false
  autorotation: true
  brushenabled: false
  brushname: 'cliff.png'
maximums:
  size: 305
  intensity: 10
disabledworlds:
  - "add disabled worlds here"
# The Material that goBrush will use
material: flint
